// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhk9sJ8NJP2CWkEhykmWzs7PyIrt1BDSk',
    appId: '1:56154688745:web:60b3dab06e3d7060763478',
    messagingSenderId: '56154688745',
    projectId: 'test-flutter-apps-192b9',
    authDomain: 'test-flutter-apps-192b9.firebaseapp.com',
    storageBucket: 'test-flutter-apps-192b9.appspot.com',
    measurementId: 'G-CHWELSEMFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrbD5_vhZdz3DcyQLSnkttAgu_rIqCF80',
    appId: '1:56154688745:android:d0466b1fbff24852763478',
    messagingSenderId: '56154688745',
    projectId: 'test-flutter-apps-192b9',
    storageBucket: 'test-flutter-apps-192b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_junfIwMyIJwUZE4YU5i1IYqA0qGGdlI',
    appId: '1:56154688745:ios:105d762043b25620763478',
    messagingSenderId: '56154688745',
    projectId: 'test-flutter-apps-192b9',
    storageBucket: 'test-flutter-apps-192b9.appspot.com',
    iosBundleId: 'com.axceldev.authFirebaseApp',
  );
}
